### ISSUE TITLE
Pokemon White/Black in Spanish

### ISSUE THREAD

**Issue by UgaTEC** [Cysha/Pokelink-issues#4]
Pokelink doesn't work because the LUA Script says: script returned but is still running registered functions

And the game (maybe cause the memory addresses changes) doesn't send the data over LUA to the Script.

**Comment by NoelDavies** [comment]
I believe we only support the English language roms, but if you send me the Rom over discord or something I'll double check for you .

**Comment by NoelDavies** [comment]
We don't currently support non-english roms
