### ISSUE TITLE
Sessions hanging/not deleting

### ISSUE THREAD

**Issue by GreasyXSpoon** [Cysha/Pokelink-issues#5]
So I'm just trying to use the system with Citra and what is occurring is when I create a new session and I pick the game I'm using, it recognises the emulator and then just sits and hangs on trying to loads the config to the pokelink and if left for about 5 minutes the system will shutdown.

I don't know what is happening in this as when i then close the system an old session that I have deleted appears as being the active session again. And even if I try to enter into that session it will just hang at the stage of trying to connect to the server which I'm more than certain is one i set myself.

Any assistance with this would be very helpful.

**Comment by NoelDavies** [comment]
Hey @GreasyXSpoon This repo is more used for us to keep track of internal issues and will be removed soon. Can you ask this on discord instead? This is an one of those issues that it'd be beneficial to see it happening.

**Comment by GreasyXSpoon** [comment]
I have, and we already been through it mate.

I'm GXS

cheers

**Comment by NoelDavies** [comment]
Ohh sorry mate my bad 😂😂
